=== griptheinfosysparaclete/IFCParaclete/MaxineCode/src/src/org/ifcparaclete/IFCPolicy.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
            targetNamespace="http://ifcparaclete.org" xmlns="http://ifcparaclete.org"
            xmlns:ifc="http://ifcparaclete.org">
    <xsd:element name="IFCPolicy">
        <xsd:annotation>
            <xsd:documentation>Schema for Information Flow Control Policies</xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="RunnableObject" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="Name">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:pattern value="^[A-Za-z0-9\._]+"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                            <xsd:element name="ID">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:pattern value="[0-9]+"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                            <xsd:element name="SecurityLevel">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:enumeration value="F"/>
                                        <xsd:enumeration value="H"/>
                                        <xsd:enumeration value="P"/>
                                        <xsd:enumeration value="U"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                            <xsd:element name="Category">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:enumeration value="A"/>
                                        <xsd:enumeration value="S"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                            <xsd:element name="Type">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:enumeration value="I"/>
                                        <xsd:enumeration value="T"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                            <xsd:element name="ActiveIFOPS">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="Op" minOccurs="0" maxOccurs="8">
                                            <xsd:simpleType>
                                                <xsd:restriction base="xsd:string">
                                                    <xsd:enumeration value="e"/>
                                                    <xsd:enumeration value="o"/>
                                                    <xsd:enumeration value="c"/>
                                                    <xsd:enumeration value="l"/>
                                                    <xsd:enumeration value="w"/>
                                                    <xsd:enumeration value="r"/>
                                                    <xsd:enumeration value="d"/>
                                                    <xsd:enumeration value="f"/>
                                                </xsd:restriction>
                                            </xsd:simpleType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="PassiveIFOPS">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="Op" minOccurs="0" maxOccurs="8">
                                            <xsd:simpleType>
                                                <xsd:restriction base="xsd:string">
                                                    <xsd:enumeration value="e"/>
                                                    <xsd:enumeration value="o"/>
                                                    <xsd:enumeration value="c"/>
                                                    <xsd:enumeration value="l"/>
                                                    <xsd:enumeration value="w"/>
                                                    <xsd:enumeration value="r"/>
                                                    <xsd:enumeration value="d"/>
                                                    <xsd:enumeration value="f"/>
                                                </xsd:restriction>
                                            </xsd:simpleType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== griptheinfosysparaclete/IFCParaclete/MaxineCode/src/org/ifcparaclete/IFCPolicy.xml
<?xml version="1.0" encoding="UTF-8" ?>
<ifc:IFCPolicy xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://ifcparaclete.org file:/Users/GripGlebe/jdeveloper/mywork/IFCParaclete/MaxineCode/src/org/ifcparaclete/IFCPolicy.xsd"
               xmlns:ifc="http://ifcparaclete.org">
    <ifc:IFCObjects>
        <ifc:ActorObjects>
            <ifc:ActorObject>
                <ifc:Name>com.sun.max.vm.run.java.JavaRunScheme</ifc:Name>
                <ifc:ID>0</ifc:ID>
                <ifc:SecurityLevel>F</ifc:SecurityLevel>
                <ifc:Category>S</ifc:Category>
                <ifc:Type>T</ifc:Type>
                <ifc:ActiveIFOPS>
                    <ifc:Op>e</ifc:Op>
                    <ifc:Op>o</ifc:Op>
                    <ifc:Op>c</ifc:Op>
                    <ifc:Op>l</ifc:Op>
                    <ifc:Op>w</ifc:Op>
                    <ifc:Op>r</ifc:Op>
                    <ifc:Op>d</ifc:Op>
                    <ifc:Op>f</ifc:Op>
                    <ifc:Op>a</ifc:Op>
                    <ifc:Op>m</ifc:Op>
                </ifc:ActiveIFOPS>
                <ifc:PassiveIFOPS>
                    <ifc:Op>e</ifc:Op>
                    <ifc:Op>o</ifc:Op>
                    <ifc:Op>c</ifc:Op>
                    <ifc:Op>l</ifc:Op>
                    <ifc:Op>w</ifc:Op>
                    <ifc:Op>r</ifc:Op>
                    <ifc:Op>d</ifc:Op>
                    <ifc:Op>f</ifc:Op>
                    <ifc:Op>a</ifc:Op>
                    <ifc:Op>m</ifc:Op>
                </ifc:PassiveIFOPS>
            </ifc:ActorObject>
            <ifc:ActorObject>
                <ifc:Name>com.sun.max.vm.hosted.HostedClassLoader</ifc:Name>
                <ifc:ID>1</ifc:ID>
                <ifc:SecurityLevel>F</ifc:SecurityLevel>
                <ifc:Category>S</ifc:Category>
                <ifc:Type>T</ifc:Type>
                <ifc:ActiveIFOPS>
                    <ifc:Op>e</ifc:Op>
                    <ifc:Op>o</ifc:Op>
                    <ifc:Op>c</ifc:Op>
                    <ifc:Op>l</ifc:Op>
                    <ifc:Op>w</ifc:Op>
                    <ifc:Op>r</ifc:Op>
                    <ifc:Op>d</ifc:Op>
                    <ifc:Op>f</ifc:Op>
                    <ifc:Op>a</ifc:Op>
                    <ifc:Op>m</ifc:Op>
                </ifc:ActiveIFOPS>
                <ifc:PassiveIFOPS>
                    <ifc:Op>e</ifc:Op>
                    <ifc:Op>o</ifc:Op>
                    <ifc:Op>c</ifc:Op>
                    <ifc:Op>l</ifc:Op>
                    <ifc:Op>w</ifc:Op>
                    <ifc:Op>r</ifc:Op>
                    <ifc:Op>d</ifc:Op>
                    <ifc:Op>f</ifc:Op>
                    <ifc:Op>a</ifc:Op>
                    <ifc:Op>m</ifc:Op>
                </ifc:PassiveIFOPS>
            </ifc:ActorObject>
            <ifc:ActorObject>
                <ifc:Name>test.output.HelloWorld</ifc:Name>
                <ifc:ID>2</ifc:ID>
                <ifc:SecurityLevel>F</ifc:SecurityLevel>
                <ifc:Category>A</ifc:Category>
                <ifc:Type>I</ifc:Type>
                <ifc:ActiveIFOPS/>
                <ifc:PassiveIFOPS>
                    <ifc:Op>e</ifc:Op>
                    <ifc:Op>o</ifc:Op>
                    <ifc:Op>c</ifc:Op>
                    <ifc:Op>l</ifc:Op>
                    <ifc:Op>w</ifc:Op>
                    <ifc:Op>r</ifc:Op>
                    <ifc:Op>d</ifc:Op>
                    <ifc:Op>f</ifc:Op>
                    <ifc:Op>a</ifc:Op>
                    <ifc:Op>m</ifc:Op>
                </ifc:PassiveIFOPS>
            </ifc:ActorObject>
        </ifc:ActorObjects>
        <ifc:TargetObjects>
            <ifc:TargetObject>
                <ifc:Name>com.sun.max.vm.run.java.JavaRunScheme</ifc:Name>
                <ifc:ID>0</ifc:ID>
                <ifc:SecurityLevel>F</ifc:SecurityLevel>
                <ifc:Category>S</ifc:Category>
                <ifc:Type>T</ifc:Type>
                <ifc:ActiveIFOPS>
                    <ifc:Op>e</ifc:Op>
                    <ifc:Op>o</ifc:Op>
                    <ifc:Op>c</ifc:Op>
                    <ifc:Op>l</ifc:Op>
                    <ifc:Op>w</ifc:Op>
                    <ifc:Op>r</ifc:Op>
                    <ifc:Op>d</ifc:Op>
                    <ifc:Op>f</ifc:Op>
                    <ifc:Op>a</ifc:Op>
                    <ifc:Op>m</ifc:Op>
                </ifc:ActiveIFOPS>
                <ifc:PassiveIFOPS>
                    <ifc:Op>e</ifc:Op>
                    <ifc:Op>o</ifc:Op>
                    <ifc:Op>c</ifc:Op>
                    <ifc:Op>l</ifc:Op>
                    <ifc:Op>w</ifc:Op>
                    <ifc:Op>r</ifc:Op>
                    <ifc:Op>d</ifc:Op>
                    <ifc:Op>f</ifc:Op>
                    <ifc:Op>a</ifc:Op>
                    <ifc:Op>m</ifc:Op>
                </ifc:PassiveIFOPS>
            </ifc:TargetObject>
            <ifc:TargetObject>
                <ifc:Name>com.sun.max.vm.hosted.HostedClassLoader</ifc:Name>
                <ifc:ID>1</ifc:ID>
                <ifc:SecurityLevel>F</ifc:SecurityLevel>
                <ifc:Category>S</ifc:Category>
                <ifc:Type>T</ifc:Type>
                <ifc:ActiveIFOPS>
                    <ifc:Op>e</ifc:Op>
                    <ifc:Op>o</ifc:Op>
                    <ifc:Op>c</ifc:Op>
                    <ifc:Op>l</ifc:Op>
                    <ifc:Op>w</ifc:Op>
                    <ifc:Op>r</ifc:Op>
                    <ifc:Op>d</ifc:Op>
                    <ifc:Op>f</ifc:Op>
                    <ifc:Op>a</ifc:Op>
                    <ifc:Op>m</ifc:Op>
                </ifc:ActiveIFOPS>
                <ifc:PassiveIFOPS>
                    <ifc:Op>e</ifc:Op>
                    <ifc:Op>o</ifc:Op>
                    <ifc:Op>c</ifc:Op>
                    <ifc:Op>l</ifc:Op>
                    <ifc:Op>w</ifc:Op>
                    <ifc:Op>r</ifc:Op>
                    <ifc:Op>d</ifc:Op>
                    <ifc:Op>f</ifc:Op>
                    <ifc:Op>a</ifc:Op>
                    <ifc:Op>m</ifc:Op>
                </ifc:PassiveIFOPS>
            </ifc:TargetObject>
            <ifc:TargetObject>
                <ifc:Name>test.output.HelloWorld</ifc:Name>
                <ifc:ID>2</ifc:ID>
                <ifc:SecurityLevel>F</ifc:SecurityLevel>
                <ifc:Category>A</ifc:Category>
                <ifc:Type>I</ifc:Type>
                <ifc:ActiveIFOPS/>
                <ifc:PassiveIFOPS>
                    <ifc:Op>e</ifc:Op>
                    <ifc:Op>o</ifc:Op>
                    <ifc:Op>c</ifc:Op>
                    <ifc:Op>l</ifc:Op>
                    <ifc:Op>w</ifc:Op>
                    <ifc:Op>r</ifc:Op>
                    <ifc:Op>d</ifc:Op>
                    <ifc:Op>f</ifc:Op>
                    <ifc:Op>a</ifc:Op>
                    <ifc:Op>m</ifc:Op>
                </ifc:PassiveIFOPS>
            </ifc:TargetObject>
            <ifc:TargetObject>
                <ifc:Name>java.lang.System</ifc:Name>
                <ifc:ID>3</ifc:ID>
                <ifc:SecurityLevel>F</ifc:SecurityLevel>
                <ifc:Category>S</ifc:Category>
                <ifc:Type>I</ifc:Type>
                <ifc:ActiveIFOPS/>
                <ifc:PassiveIFOPS>
                    <ifc:Op>e</ifc:Op>
                    <ifc:Op>o</ifc:Op>
                    <ifc:Op>c</ifc:Op>
                    <ifc:Op>l</ifc:Op>
                    <ifc:Op>w</ifc:Op>
                    <ifc:Op>r</ifc:Op>
                    <ifc:Op>d</ifc:Op>
                    <ifc:Op>f</ifc:Op>
                    <ifc:Op>a</ifc:Op>
                    <ifc:Op>m</ifc:Op>
                </ifc:PassiveIFOPS>
            </ifc:TargetObject>
        </ifc:TargetObjects>
    </ifc:IFCObjects>
</ifc:IFCPolicy>

=== griptheinfosysparaclete/IFCParaclete/MaxineCode/src/src/org/ifcparaclete/IFCPolicy.xml
<?xml version="1.0" encoding="UTF-8" ?>
<ifc:IFCPolicy xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://ifcparaclete.org                 file:/Users/GripGlebe/jdeveloper/mywork/IFCParaclete/IFCDissertationCode/src/org/ifcparaclete/ IFCPolicy.xsd"
               xmlns:ifc="http://ifcparaclete.org">
    <ifc:RunnableObject>
        <ifc:Name>com.sun.max.asm.dis.Disassembler</ifc:Name>
        <ifc:ID>0</ifc:ID>
        <ifc:SecurityLevel>F</ifc:SecurityLevel>
        <ifc:Category>A</ifc:Category>
        <ifc:Type>I</ifc:Type>
        <ifc:ActiveIFOPS></ifc:ActiveIFOPS>
        <ifc:Op>e</ifc:Op>
        <ifc:Op>o</ifc:Op>
        <ifc:Op>c</ifc:Op>
        <ifc:Op>l</ifc:Op>
        <ifc:Op>w</ifc:Op>
        <ifc:Op>r</ifc:Op>
        <ifc:Op>d</ifc:Op>
        <ifc:Op>f</ifc:Op>
        <ifc:PassiveIFOPS>
            <ifc:Op>e</ifc:Op>
            <ifc:Op>o</ifc:Op>
            <ifc:Op>c</ifc:Op>
            <ifc:Op>l</ifc:Op>
            <ifc:Op>w</ifc:Op>
            <ifc:Op>r</ifc:Op>
            <ifc:Op>d</ifc:Op>
            <ifc:Op>f</ifc:Op>
        </ifc:PassiveIFOPS>
    </ifc:RunnableObject>
    <ifc:RunnableObject>
        <ifc:Name>test.output.HelloWorld</ifc:Name>
        <ifc:ID>1</ifc:ID>
        <ifc:SecurityLevel>F</ifc:SecurityLevel>
        <ifc:Category>A</ifc:Category>
        <ifc:Type>I</ifc:Type>
        <ifc:ActiveIFOPS/>
        <ifc:PassiveIFOPS>
            <ifc:Op>e</ifc:Op>
            <ifc:Op>o</ifc:Op>
            <ifc:Op>c</ifc:Op>
            <ifc:Op>l</ifc:Op>
            <ifc:Op>w</ifc:Op>
            <ifc:Op>r</ifc:Op>
            <ifc:Op>d</ifc:Op>
            <ifc:Op>f</ifc:Op>
        </ifc:PassiveIFOPS>
    </ifc:RunnableObject>
    <ifc:RunnableObject>
        <ifc:Name>HelloWorld</ifc:Name>
        <ifc:ID>2</ifc:ID>
        <ifc:SecurityLevel>F</ifc:SecurityLevel>
        <ifc:Category>A</ifc:Category>
        <ifc:Type>I</ifc:Type>
        <ifc:ActiveIFOPS/>
        <ifc:PassiveIFOPS>
            <ifc:Op>e</ifc:Op>
            <ifc:Op>o</ifc:Op>
            <ifc:Op>c</ifc:Op>
            <ifc:Op>l</ifc:Op>
            <ifc:Op>w</ifc:Op>
            <ifc:Op>r</ifc:Op>
            <ifc:Op>d</ifc:Op>
            <ifc:Op>f</ifc:Op>
        </ifc:PassiveIFOPS>
    </ifc:RunnableObject>
    <ifc:RunnableObject>
        <ifc:Name>IFCTesting.HelloWorld</ifc:Name>
        <ifc:ID>3</ifc:ID>
        <ifc:SecurityLevel>F</ifc:SecurityLevel>
        <ifc:Category>A</ifc:Category>
        <ifc:Type>I</ifc:Type>
        <ifc:ActiveIFOPS/>
        <ifc:PassiveIFOPS>
            <ifc:Op>e</ifc:Op>
            <ifc:Op>o</ifc:Op>
            <ifc:Op>c</ifc:Op>
            <ifc:Op>l</ifc:Op>
            <ifc:Op>w</ifc:Op>
            <ifc:Op>r</ifc:Op>
            <ifc:Op>d</ifc:Op>
            <ifc:Op>f</ifc:Op>
        </ifc:PassiveIFOPS>
    </ifc:RunnableObject>
    <ifc:RunnableObject>
        <ifc:Name>IFCTest_1</ifc:Name>
        <ifc:ID>4</ifc:ID>
        <ifc:SecurityLevel>U</ifc:SecurityLevel>
        <ifc:Category>A</ifc:Category>
        <ifc:Type>I</ifc:Type>
        <ifc:ActiveIFOPS></ifc:ActiveIFOPS>
        <ifc:PassiveIFOPS>
            <ifc:Op>e</ifc:Op>
            <ifc:Op>o</ifc:Op>
            <ifc:Op>c</ifc:Op>
            <ifc:Op>l</ifc:Op>
            <ifc:Op>w</ifc:Op>
            <ifc:Op>r</ifc:Op>
            <ifc:Op>d</ifc:Op>
            <ifc:Op>f</ifc:Op>
        </ifc:PassiveIFOPS>
    </ifc:RunnableObject>
    <ifc:RunnableObject>
        <ifc:Name>IFCTest_2</ifc:Name>
        <ifc:ID>5</ifc:ID>
        <ifc:SecurityLevel>P</ifc:SecurityLevel>
        <ifc:Category>A</ifc:Category>
        <ifc:Type>I</ifc:Type>
        <ifc:ActiveIFOPS/>
        <ifc:PassiveIFOPS>
            <ifc:Op>e</ifc:Op>
            <ifc:Op>o</ifc:Op>
            <ifc:Op>c</ifc:Op>
            <ifc:Op>l</ifc:Op>
            <ifc:Op>w</ifc:Op>
            <ifc:Op>r</ifc:Op>
            <ifc:Op>d</ifc:Op>
            <ifc:Op>f</ifc:Op>
        </ifc:PassiveIFOPS>
    </ifc:RunnableObject>
    <ifc:RunnableObject>
        <ifc:Name>IFCTest_3</ifc:Name>
        <ifc:ID>6</ifc:ID>
        <ifc:SecurityLevel>H</ifc:SecurityLevel>
        <ifc:Category>A</ifc:Category>
        <ifc:Type>I</ifc:Type>
        <ifc:ActiveIFOPS/>
        <ifc:PassiveIFOPS>
            <ifc:Op>e</ifc:Op>
            <ifc:Op>o</ifc:Op>
            <ifc:Op>c</ifc:Op>
            <ifc:Op>l</ifc:Op>
            <ifc:Op>w</ifc:Op>
            <ifc:Op>r</ifc:Op>
            <ifc:Op>d</ifc:Op>
            <ifc:Op>f</ifc:Op>
        </ifc:PassiveIFOPS>
    </ifc:RunnableObject>
    <ifc:RunnableObject>
        <ifc:Name>IFCTest_4</ifc:Name>
        <ifc:ID>7</ifc:ID>
        <ifc:SecurityLevel>F</ifc:SecurityLevel>
        <ifc:Category>A</ifc:Category>
        <ifc:Type>I</ifc:Type>
        <ifc:ActiveIFOPS/>
        <ifc:PassiveIFOPS>
            <ifc:Op>e</ifc:Op>
            <ifc:Op>o</ifc:Op>
            <ifc:Op>c</ifc:Op>
            <ifc:Op>l</ifc:Op>
            <ifc:Op>w</ifc:Op>
            <ifc:Op>r</ifc:Op>
            <ifc:Op>d</ifc:Op>
            <ifc:Op>f</ifc:Op>
        </ifc:PassiveIFOPS>
    </ifc:RunnableObject>
</ifc:IFCPolicy>
